import './globals.css'
import Navbar from './components/navbar'
import ProfilePic from './components/ProfilePic'
import { UserProvider } from '@auth0/nextjs-auth0/client';

export const metadata = {
  title: "Adrian's Blog",
  description: 'Generated by Adrian. practicing for future use..',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className="dark:bg-slate-800">
          <Navbar />
          <ProfilePic />
        {children}
        <a href="/api/auth/login">Login</a>
        </body>
      </UserProvider>
    </html>
  )
}
