import './globals.css'
import Navbar from './components/Navbar'
import ProfilePic from './components/ProfilePic'

export const metadata: Metadata = {
  title: "Adrian's Blog",
  description: 'Generated by Adrian practicing for future use',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800">
        <Navbar />
        <ProfilePic />
      {children}
      </body>
    </html>
  )
}
